# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:            Snf's blog
tagline:
url:
paginate:         1
baseurl:          /
# baseurl:        ""
author:
  name:           S.N. Fernandez
  url:
  email:

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# Custom vars
version:             2.0.0
github:

# pages_list:
#   About: '/about'
#   Archive: '/archive'
#   Feed: '/atom.xml'

# Gems
plugins:
  - jekyll-paginate
#  - jekyll-gist
