# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Snf's blog
tagline:          
url:              
paginate:         1
baseurl:          /
author:
  name:           S.N. Fernandez
  url:            
  email:          

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
